name = "cloudflare-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "todo-db-local"
migrations_dir = "migrations"
